name: CI

on: [push, pull_request]

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust (stable)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: actions/checkout@v3

      - name: Check formatting
        run: cargo fmt -- --check

      - uses: 10XGenomics/clippy-check@39a72b450310c63d1ee747a1f6039580eb7f6153
        with:
          args: --all-features

      - run: cargo check

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly, '1.60']
        cargo-update-flags: ['']
        features:
          - ''
          - '--no-default-features'
        include:
          - toolchain: nightly
            cargo-update-flags: '-Z minimal-versions'
            features: ''
          - toolchain: nightly
            cargo-update-flags: '-Z minimal-versions'
            features: '--no-default-features'

    steps:
      - name: Install Rust (${{ matrix.toolchain }})
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy, rustfmt

      - uses: actions/checkout@v3

      - name: Adjust dependencies ${{ matrix.cargo-update-flags }}
        if: matrix.cargo-update-flags
        run: cargo update ${{ matrix.cargo-update-flags }}

      - name: Run tests
        run: cargo test ${{ matrix.features }}
