name: CI

on: [push, pull_request]

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1

      - name: Check formatting
        run: cargo fmt -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly, '1.57']
        features:
          - ''
          - '--no-default-features'

    steps:
      - name: Install Rust (${{ matrix.toolchain }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          default: true
          components: clippy, rustfmt

      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.features }}
